// data.js

import { v4 as uuidv4 } from "uuid";

// // Set the app element for accessibility
// Modal.setAppElement("#root");

// const UserData = () => {
//   const [filterInput, setFilterInput] = useState("");
//   const [expandedRow, setExpandedRow] = useState(null);

//   useEffect(() => {
//     // Generate unique IDs for existing data without a userIdNumber
//     data.forEach((item) => {
//       if (!item.userIdNumber) {
//         item.userIdNumber = uuidv4();
//       }
//     });
//   }, []);

//   const handleFilterChange = (e) => {
//     const value = e.target.value || undefined;
//     setGlobalFilter(value);
//     setFilterInput(value);
//   };

//   data accessors
//   reportStatus  // this is the status of the report [verified, pending]
//   reportDate    // this is the report data and time
//   reportIdNumber  // every report will have a unique idnumber that can be identified, like a ticket so when the specific reports have some anomaly it can be save as a reference
//   reportImage   // reports will have it picture uploaded to the web for the verification of the reports. images taken can also be use to enhance the machine learning model 
//   coordinates   // automated coordinate tracker to track the said report in the map
//   fishDisease   // fish disease that will be i dentified by the model

//   userIdNumber: uuidv4(),
//   region: "Region 1",
//   province: "Province 1",
//   cityTown: "City 1",
//   address: "Address 1",
//   firstName: "John",
//   middleName: "Doe",
//   lastName: "Smith",
//   telephone: "1234567890",
//   mobileNumber: "0987654321",
//   email: "john@example.com",
//   birthdate: "1990-01-01",
//   placeOfBirth: "Place 1",
//   sex: "Male",
//   civilStatus: "Single",
//   bloodType: "A",
//   religion: "Religion 1",
//   nationality: "Nationality 1",
//   highestEducationalAttainment: "Bachelor's Degree",
//   emergencyContact: "Jane Doe",
//   emergencyContactNumber: "1234567890",
//   emergrncyRelationship: "Sister",
//   emergrncyAddress: "Address 2",
//   mainSourceofIncome: "Job 1",
//   mainSourceofIncomeAmount: 50000,
//   otherSourceofIncome: "Job 2",
//   otherSourceofIncomeAmount: 20000,
//   nameofOrganization: "Org 1",
//   memberSince: "2020-01-01",
//   positioninOrganization: "Member",
//   nameofSpouse: "Spouse 1",
//   numberofchildren: 2,
//   spouseContactnum: "1234567890",
//   numberofchildreninSchool: 1,
//   numberofchildrenoutSchool: 1,
//   numberofEmployedfammem: 2,
//   numberofUnemployedfammem: 1,
// },

// Sample data (replace with actual data as needed)
export const data = [
  {
    userIdNumber: uuidv4(),
    region: "Region 1",
    province: "Province 1",
    cityTown: "City 1",
    address: "Address 1",
    firstName: "John",
    middleName: "Doe",
    lastName: "Smith",
    telephone: "1234567890",
    mobileNumber: "0987654321",
    email: "john@example.com",
    birthdate: "1990-01-01",
    placeOfBirth: "Place 1",
    sex: "Male",
    civilStatus: "Single",
    bloodType: "A",
    religion: "Religion 1",
    nationality: "Nationality 1",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Jane Doe",
    emergencyContactNumber: "1234567890",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 2",
    mainSourceofIncome: "Job 1",
    mainSourceofIncomeAmount: 50000,
    otherSourceofIncome: "Job 2",
    otherSourceofIncomeAmount: 20000,
    nameofOrganization: "Org 1",
    memberSince: "2020-01-01",
    positioninOrganization: "Member",
    nameofSpouse: "Spouse 1",
    numberofchildren: 2,
    spouseContactnum: "1234567890",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 2",
    province: "Province 2",
    cityTown: "City 2",
    address: "Address 2",
    firstName: "Jane",
    middleName: "Evelyn",
    lastName: "Doe",
    telephone: "2345678901",
    mobileNumber: "0876543210",
    email: "jane@example.com",
    birthdate: "1995-05-15",
    placeOfBirth: "Place 2",
    sex: "Female",
    civilStatus: "Married",
    bloodType: "B",
    religion: "Religion 2",
    nationality: "Nationality 2",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "John Doe",
    emergencyContactNumber: "2345678901",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 3",
    mainSourceofIncome: "Job 3",
    mainSourceofIncomeAmount: 60000,
    otherSourceofIncome: "Job 4",
    otherSourceofIncomeAmount: 25000,
    nameofOrganization: "Org 2",
    memberSince: "2018-07-01",
    positioninOrganization: "Director",
    nameofSpouse: "Spouse 2",
    numberofchildren: 1,
    spouseContactnum: "2345678901",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 3,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 3",
    province: "Province 3",
    cityTown: "City 3",
    address: "Address 3",
    firstName: "Michael",
    middleName: "David",
    lastName: "Johnson",
    telephone: "3456789012",
    mobileNumber: "0765432109",
    email: "michael@example.com",
    birthdate: "1988-12-10",
    placeOfBirth: "Place 3",
    sex: "Male",
    civilStatus: "Divorced",
    bloodType: "O",
    religion: "Religion 3",
    nationality: "Nationality 3",
    highestEducationalAttainment: "PhD",
    emergencyContact: "Sarah Johnson",
    emergencyContactNumber: "3456789012",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 4",
    mainSourceofIncome: "Consulting",
    mainSourceofIncomeAmount: 80000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 3",
    memberSince: "2015-03-20",
    positioninOrganization: "Manager",
    nameofSpouse: "Spouse 3",
    numberofchildren: 3,
    spouseContactnum: "3456789012",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 4",
    province: "Province 4",
    cityTown: "City 4",
    address: "Address 4",
    firstName: "Emily",
    middleName: "Grace",
    lastName: "Williams",
    telephone: "4567890123",
    mobileNumber: "0654321098",
    email: "emily@example.com",
    birthdate: "1992-08-22",
    placeOfBirth: "Place 4",
    sex: "Female",
    civilStatus: "Single",
    bloodType: "AB",
    religion: "Religion 4",
    nationality: "Nationality 4",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "David Williams",
    emergencyContactNumber: "4567890123",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 5",
    mainSourceofIncome: "Business",
    mainSourceofIncomeAmount: 70000,
    otherSourceofIncome: "Freelancing",
    otherSourceofIncomeAmount: 20000,
    nameofOrganization: "Org 4",
    memberSince: "2017-01-15",
    positioninOrganization: "Coordinator",
    nameofSpouse: "Spouse 4",
    numberofchildren: 0,
    spouseContactnum: "4567890123",
    numberofchildreninSchool: 0,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 1,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 5",
    province: "Province 5",
    cityTown: "City 5",
    address: "Address 5",
    firstName: "Sarah",
    middleName: "Ann",
    lastName: "Brown",
    telephone: "5678901234",
    mobileNumber: "0543210987",
    email: "sarah@example.com",
    birthdate: "1985-04-18",
    placeOfBirth: "Place 5",
    sex: "Female",
    civilStatus: "Married",
    bloodType: "B",
    religion: "Religion 5",
    nationality: "Nationality 5",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Mark Brown",
    emergencyContactNumber: "5678901234",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 6",
    mainSourceofIncome: "Government Job",
    mainSourceofIncomeAmount: 90000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 40000,
    nameofOrganization: "Org 5",
    memberSince: "2016-06-30",
    positioninOrganization: "CEO",
    nameofSpouse: "Spouse 5",
    numberofchildren: 2,
    spouseContactnum: "5678901234",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 4,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 6",
    province: "Province 6",
    cityTown: "City 6",
    address: "Address 6",
    firstName: "Daniel",
    middleName: "Joseph",
    lastName: "Miller",
    telephone: "6789012345",
    mobileNumber: "0432109876",
    email: "daniel@example.com",
    birthdate: "1993-11-05",
    placeOfBirth: "Place 6",
    sex: "Male",
    civilStatus: "Single",
    bloodType: "O",
    religion: "Religion 6",
    nationality: "Nationality 6",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Emma Miller",
    emergencyContactNumber: "6789012345",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 7",
    mainSourceofIncome: "Tech Startup",
    mainSourceofIncomeAmount: 120000,
    otherSourceofIncome: "Consulting",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 6",
    memberSince: "2019-05-20",
    positioninOrganization: "Consultant",
    nameofSpouse: "Spouse 6",
    numberofchildren: 1,
    spouseContactnum: "6789012345",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 7",
    province: "Province 7",
    cityTown: "City 7",
    address: "Address 7",
    firstName: "Melissa",
    middleName: "Anne",
    lastName: "Martinez",
    telephone: "7890123456",
    mobileNumber: "0321098765",
    email: "melissa@example.com",
    birthdate: "1997-07-25",
    placeOfBirth: "Place 7",
    sex: "Female",
    civilStatus: "Single",
    bloodType: "AB",
    religion: "Religion 7",
    nationality: "Nationality 7",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Carlos Martinez",
    emergencyContactNumber: "7890123456",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 8",
    mainSourceofIncome: "Accounting",
    mainSourceofIncomeAmount: 85000,
    otherSourceofIncome: "Freelancing",
    otherSourceofIncomeAmount: 15000,
    nameofOrganization: "Org 7",
    memberSince: "2020-10-12",
    positioninOrganization: "Accountant",
    nameofSpouse: "Spouse 7",
    numberofchildren: 0,
    spouseContactnum: "7890123456",
    numberofchildreninSchool: 0,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 1,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 8",
    province: "Province 8",
    cityTown: "City 8",
    address: "Address 8",
    firstName: "Christopher",
    middleName: "Thomas",
    lastName: "Taylor",
    telephone: "8901234567",
    mobileNumber: "0210987654",
    email: "christopher@example.com",
    birthdate: "1983-02-08",
    placeOfBirth: "Place 8",
    sex: "Male",
    civilStatus: "Married",
    bloodType: "A",
    religion: "Religion 8",
    nationality: "Nationality 8",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Laura Taylor",
    emergencyContactNumber: "8901234567",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 9",
    mainSourceofIncome: "Engineering",
    mainSourceofIncomeAmount: 95000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 50000,
    nameofOrganization: "Org 8",
    memberSince: "2014-04-05",
    positioninOrganization: "Engineer",
    nameofSpouse: "Spouse 8",
    numberofchildren: 2,
    spouseContactnum: "8901234567",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 3,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 9",
    province: "Province 9",
    cityTown: "City 9",
    address: "Address 9",
    firstName: "Amanda",
    middleName: "Nicole",
    lastName: "Adams",
    telephone: "9012345678",
    mobileNumber: "0109876543",
    email: "amanda@example.com",
    birthdate: "1987-11-30",
    placeOfBirth: "Place 9",
    sex: "Female",
    civilStatus: "Divorced",
    bloodType: "O",
    religion: "Religion 9",
    nationality: "Nationality 9",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Brian Adams",
    emergencyContactNumber: "9012345678",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 10",
    mainSourceofIncome: "Marketing",
    mainSourceofIncomeAmount: 75000,
    otherSourceofIncome: "Consulting",
    otherSourceofIncomeAmount: 25000,
    nameofOrganization: "Org 9",
    memberSince: "2016-09-18",
    positioninOrganization: "Marketing Manager",
    nameofSpouse: "Spouse 9",
    numberofchildren: 1,
    spouseContactnum: "9012345678",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 10",
    province: "Province 10",
    cityTown: "City 10",
    address: "Address 10",
    firstName: "Ryan",
    middleName: "Patrick",
    lastName: "Thomas",
    telephone: "0123456789",
    mobileNumber: "0987654321",
    email: "ryan@example.com",
    birthdate: "1991-03-12",
    placeOfBirth: "Place 10",
    sex: "Male",
    civilStatus: "Single",
    bloodType: "A",
    religion: "Religion 10",
    nationality: "Nationality 10",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Karen Thomas",
    emergencyContactNumber: "0123456789",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 11",
    mainSourceofIncome: "Finance",
    mainSourceofIncomeAmount: 110000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 40000,
    nameofOrganization: "Org 10",
    memberSince: "2018-12-25",
    positioninOrganization: "Financial Analyst",
    nameofSpouse: "Spouse 10",
    numberofchildren: 0,
    spouseContactnum: "0123456789",
    numberofchildreninSchool: 0,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 1,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 11",
    province: "Province 11",
    cityTown: "City 11",
    address: "Address 11",
    firstName: "Emma",
    middleName: "Rose",
    lastName: "Garcia",
    telephone: "1234567890",
    mobileNumber: "0987654321",
    email: "emma@example.com",
    birthdate: "1994-06-20",
    placeOfBirth: "Place 11",
    sex: "Female",
    civilStatus: "Married",
    bloodType: "O",
    religion: "Religion 11",
    nationality: "Nationality 11",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Carlos Garcia",
    emergencyContactNumber: "1234567890",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 12",
    mainSourceofIncome: "Engineering",
    mainSourceofIncomeAmount: 95000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 50000,
    nameofOrganization: "Org 11",
    memberSince: "2014-04-05",
    positioninOrganization: "Engineer",
    nameofSpouse: "Spouse 11",
    numberofchildren: 2,
    spouseContactnum: "1234567890",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 3,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 12",
    province: "Province 12",
    cityTown: "City 12",
    address: "Address 12",
    firstName: "Olivia",
    middleName: "Grace",
    lastName: "Rodriguez",
    telephone: "2345678901",
    mobileNumber: "0876543210",
    email: "olivia@example.com",
    birthdate: "1996-09-12",
    placeOfBirth: "Place 12",
    sex: "Female",
    civilStatus: "Single",
    bloodType: "AB",
    religion: "Religion 12",
    nationality: "Nationality 12",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "David Rodriguez",
    emergencyContactNumber: "2345678901",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 13",
    mainSourceofIncome: "Business",
    mainSourceofIncomeAmount: 70000,
    otherSourceofIncome: "Freelancing",
    otherSourceofIncomeAmount: 20000,
    nameofOrganization: "Org 12",
    memberSince: "2017-01-15",
    positioninOrganization: "Coordinator",
    nameofSpouse: "Spouse 12",
    numberofchildren: 0,
    spouseContactnum: "2345678901",
    numberofchildreninSchool: 0,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 1,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 13",
    province: "Province 13",
    cityTown: "City 13",
    address: "Address 13",
    firstName: "Sophia",
    middleName: "Nicole",
    lastName: "Lopez",
    telephone: "3456789012",
    mobileNumber: "0765432109",
    email: "sophia@example.com",
    birthdate: "1989-12-05",
    placeOfBirth: "Place 13",
    sex: "Female",
    civilStatus: "Divorced",
    bloodType: "A",
    religion: "Religion 13",
    nationality: "Nationality 13",
    highestEducationalAttainment: "PhD",
    emergencyContact: "Sarah Lopez",
    emergencyContactNumber: "3456789012",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 14",
    mainSourceofIncome: "Consulting",
    mainSourceofIncomeAmount: 80000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 13",
    memberSince: "2015-03-20",
    positioninOrganization: "Manager",
    nameofSpouse: "Spouse 13",
    numberofchildren: 3,
    spouseContactnum: "3456789012",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 14",
    province: "Province 14",
    cityTown: "City 14",
    address: "Address 14",
    firstName: "Alexander",
    middleName: "James",
    lastName: "Young",
    telephone: "4567890123",
    mobileNumber: "0654321098",
    email: "alexander@example.com",
    birthdate: "1993-04-30",
    placeOfBirth: "Place 14",
    sex: "Male",
    civilStatus: "Single",
    bloodType: "O",
    religion: "Religion 14",
    nationality: "Nationality 14",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Emily Young",
    emergencyContactNumber: "4567890123",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 15",
    mainSourceofIncome: "Tech Startup",
    mainSourceofIncomeAmount: 120000,
    otherSourceofIncome: "Consulting",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 14",
    memberSince: "2019-05-20",
    positioninOrganization: "Consultant",
    nameofSpouse: "Spouse 14",
    numberofchildren: 1,
    spouseContactnum: "4567890123",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 15",
    province: "Province 15",
    cityTown: "City 15",
    address: "Address 15",
    firstName: "Mia",
    middleName: "Elizabeth",
    lastName: "Martinez",
    telephone: "5678901234",
    mobileNumber: "0543210987",
    email: "mia@example.com",
    birthdate: "1986-11-15",
    placeOfBirth: "Place 15",
    sex: "Female",
    civilStatus: "Married",
    bloodType: "B",
    religion: "Religion 15",
    nationality: "Nationality 15",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Mark Martinez",
    emergencyContactNumber: "5678901234",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 16",
    mainSourceofIncome: "Government Job",
    mainSourceofIncomeAmount: 90000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 40000,
    nameofOrganization: "Org 15",
    memberSince: "2016-06-30",
    positioninOrganization: "CEO",
    nameofSpouse: "Spouse 15",
    numberofchildren: 2,
    spouseContactnum: "5678901234",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 4,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 16",
    province: "Province 16",
    cityTown: "City 16",
    address: "Address 16",
    firstName: "William",
    middleName: "Thomas",
    lastName: "Scott",
    telephone: "6789012345",
    mobileNumber: "0432109876",
    email: "william@example.com",
    birthdate: "1982-08-05",
    placeOfBirth: "Place 16",
    sex: "Male",
    civilStatus: "Married",
    bloodType: "A",
    religion: "Religion 16",
    nationality: "Nationality 16",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Laura Scott",
    emergencyContactNumber: "6789012345",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 17",
    mainSourceofIncome: "Engineering",
    mainSourceofIncomeAmount: 95000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 50000,
    nameofOrganization: "Org 16",
    memberSince: "2014-04-05",
    positioninOrganization: "Engineer",
    nameofSpouse: "Spouse 16",
    numberofchildren: 2,
    spouseContactnum: "6789012345",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 3,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 17",
    province: "Province 17",
    cityTown: "City 17",
    address: "Address 17",
    firstName: "Elijah",
    middleName: "Andrew",
    lastName: "Lewis",
    telephone: "7890123456",
    mobileNumber: "0321098765",
    email: "elijah@example.com",
    birthdate: "1995-07-10",
    placeOfBirth: "Place 17",
    sex: "Male",
    civilStatus: "Single",
    bloodType: "AB",
    religion: "Religion 17",
    nationality: "Nationality 17",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Sophie Lewis",
    emergencyContactNumber: "7890123456",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 18",
    mainSourceofIncome: "Business",
    mainSourceofIncomeAmount: 70000,
    otherSourceofIncome: "Freelancing",
    otherSourceofIncomeAmount: 20000,
    nameofOrganization: "Org 17",
    memberSince: "2017-01-15",
    positioninOrganization: "Coordinator",
    nameofSpouse: "Spouse 17",
    numberofchildren: 0,
    spouseContactnum: "7890123456",
    numberofchildreninSchool: 0,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 1,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 18",
    province: "Province 18",
    cityTown: "City 18",
    address: "Address 18",
    firstName: "Isabella",
    middleName: "Grace",
    lastName: "Roberts",
    telephone: "8901234567",
    mobileNumber: "0210987654",
    email: "isabella@example.com",
    birthdate: "1990-02-15",
    placeOfBirth: "Place 18",
    sex: "Female",
    civilStatus: "Divorced",
    bloodType: "O",
    religion: "Religion 18",
    nationality: "Nationality 18",
    highestEducationalAttainment: "PhD",
    emergencyContact: "David Roberts",
    emergencyContactNumber: "8901234567",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 19",
    mainSourceofIncome: "Consulting",
    mainSourceofIncomeAmount: 80000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 18",
    memberSince: "2015-03-20",
    positioninOrganization: "Manager",
    nameofSpouse: "Spouse 18",
    numberofchildren: 3,
    spouseContactnum: "8901234567",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 19",
    province: "Province 19",
    cityTown: "City 19",
    address: "Address 19",
    firstName: "James",
    middleName: "Alexander",
    lastName: "Brown",
    telephone: "9012345678",
    mobileNumber: "0109876543",
    email: "james@example.com",
    birthdate: "1994-05-01",
    placeOfBirth: "Place 19",
    sex: "Male",
    civilStatus: "Single",
    bloodType: "O",
    religion: "Religion 19",
    nationality: "Nationality 19",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Emily Brown",
    emergencyContactNumber: "9012345678",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 20",
    mainSourceofIncome: "Tech Startup",
    mainSourceofIncomeAmount: 120000,
    otherSourceofIncome: "Consulting",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 19",
    memberSince: "2019-05-20",
    positioninOrganization: "Consultant",
    nameofSpouse: "Spouse 19",
    numberofchildren: 1,
    spouseContactnum: "9012345678",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 20",
    province: "Province 20",
    cityTown: "City 20",
    address: "Address 20",
    firstName: "Emily",
    middleName: "Sophia",
    lastName: "King",
    telephone: "0123456789",
    mobileNumber: "1098765432",
    email: "emily@example.com",
    birthdate: "1987-10-20",
    placeOfBirth: "Place 20",
    sex: "Female",
    civilStatus: "Married",
    bloodType: "B",
    religion: "Religion 20",
    nationality: "Nationality 20",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Mark King",
    emergencyContactNumber: "0123456789",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 21",
    mainSourceofIncome: "Government Job",
    mainSourceofIncomeAmount: 90000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 40000,
    nameofOrganization: "Org 20",
    memberSince: "2016-06-30",
    positioninOrganization: "CEO",
    nameofSpouse: "Spouse 20",
    numberofchildren: 2,
    spouseContactnum: "0123456789",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 4,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 21",
    province: "Province 21",
    cityTown: "City 21",
    address: "Address 21",
    firstName: "Adam",
    middleName: "Michael",
    lastName: "Brown",
    telephone: "2109876543",
    mobileNumber: "0678901234",
    email: "adam@example.com",
    birthdate: "1984-09-28",
    placeOfBirth: "Place 21",
    sex: "Male",
    civilStatus: "Married",
    bloodType: "O",
    religion: "Religion 21",
    nationality: "Nationality 21",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Emma Brown",
    emergencyContactNumber: "2109876543",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 22",
    mainSourceofIncome: "IT Consultant",
    mainSourceofIncomeAmount: 100000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 50000,
    nameofOrganization: "Org 21",
    memberSince: "2013-11-10",
    positioninOrganization: "Senior Consultant",
    nameofSpouse: "Spouse 21",
    numberofchildren: 2,
    spouseContactnum: "2109876543",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 3,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 22",
    province: "Province 22",
    cityTown: "City 22",
    address: "Address 22",
    firstName: "Rachel",
    middleName: "Elise",
    lastName: "Collins",
    telephone: "3210987654",
    mobileNumber: "0567890123",
    email: "rachel@example.com",
    birthdate: "1990-12-15",
    placeOfBirth: "Place 22",
    sex: "Female",
    civilStatus: "Single",
    bloodType: "A",
    religion: "Religion 22",
    nationality: "Nationality 22",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Peter Collins",
    emergencyContactNumber: "3210987654",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 23",
    mainSourceofIncome: "Software Developer",
    mainSourceofIncomeAmount: 90000,
    otherSourceofIncome: "Freelance Writing",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 22",
    memberSince: "2015-08-20",
    positioninOrganization: "Developer",
    nameofSpouse: "Spouse 22",
    numberofchildren: 0,
    spouseContactnum: "3210987654",
    numberofchildreninSchool: 0,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 1,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 23",
    province: "Province 23",
    cityTown: "City 23",
    address: "Address 23",
    firstName: "Ethan",
    middleName: "James",
    lastName: "Garcia",
    telephone: "4321098765",
    mobileNumber: "0456789012",
    email: "ethan@example.com",
    birthdate: "1986-07-20",
    placeOfBirth: "Place 23",
    sex: "Male",
    civilStatus: "Married",
    bloodType: "AB",
    religion: "Religion 23",
    nationality: "Nationality 23",
    highestEducationalAttainment: "PhD",
    emergencyContact: "Olivia Garcia",
    emergencyContactNumber: "4321098765",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 24",
    mainSourceofIncome: "Professor",
    mainSourceofIncomeAmount: 110000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 60000,
    nameofOrganization: "Org 23",
    memberSince: "2014-02-18",
    positioninOrganization: "Professor",
    nameofSpouse: "Spouse 23",
    numberofchildren: 2,
    spouseContactnum: "4321098765",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 3,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 24",
    province: "Province 24",
    cityTown: "City 24",
    address: "Address 24",
    firstName: "Olivia",
    middleName: "Grace",
    lastName: "Young",
    telephone: "5432109876",
    mobileNumber: "0789012345",
    email: "olivia@example.com",
    birthdate: "1993-04-25",
    placeOfBirth: "Place 24",
    sex: "Female",
    civilStatus: "Single",
    bloodType: "B",
    religion: "Religion 24",
    nationality: "Nationality 24",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Andrew Young",
    emergencyContactNumber: "5432109876",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 25",
    mainSourceofIncome: "Graphic Designer",
    mainSourceofIncomeAmount: 80000,
    otherSourceofIncome: "Freelance Photography",
    otherSourceofIncomeAmount: 25000,
    nameofOrganization: "Org 24",
    memberSince: "2017-05-15",
    positioninOrganization: "Designer",
    nameofSpouse: "Spouse 24",
    numberofchildren: 0,
    spouseContactnum: "5432109876",
    numberofchildreninSchool: 0,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 1,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 25",
    province: "Province 25",
    cityTown: "City 25",
    address: "Address 25",
    firstName: "Nathan",
    middleName: "Alexander",
    lastName: "Hill",
    telephone: "6543210987",
    mobileNumber: "0876543210",
    email: "nathan@example.com",
    birthdate: "1988-11-10",
    placeOfBirth: "Place 25",
    sex: "Male",
    civilStatus: "Married",
    bloodType: "A",
    religion: "Religion 25",
    nationality: "Nationality 25",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Sophia Hill",
    emergencyContactNumber: "6543210987",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 26",
    mainSourceofIncome: "Lawyer",
    mainSourceofIncomeAmount: 120000,
    otherSourceofIncome: "Real Estate",
    otherSourceofIncomeAmount: 40000,
    nameofOrganization: "Org 25",
    memberSince: "2013-09-30",
    positioninOrganization: "Attorney",
    nameofSpouse: "Spouse 25",
    numberofchildren: 2,
    spouseContactnum: "6543210987",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 3,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 21",
    province: "Province 21",
    cityTown: "City 21",
    address: "Address 21",
    firstName: "Noah",
    middleName: "Daniel",
    lastName: "Taylor",
    telephone: "1234567890",
    mobileNumber: "0987654321",
    email: "noah@example.com",
    birthdate: "1991-11-25",
    placeOfBirth: "Place 21",
    sex: "Male",
    civilStatus: "Married",
    bloodType: "A",
    religion: "Religion 21",
    nationality: "Nationality 21",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Sophie Taylor",
    emergencyContactNumber: "1234567890",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 22",
    mainSourceofIncome: "Engineering",
    mainSourceofIncomeAmount: 95000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 50000,
    nameofOrganization: "Org 21",
    memberSince: "2014-04-05",
    positioninOrganization: "Engineer",
    nameofSpouse: "Spouse 21",
    numberofchildren: 2,
    spouseContactnum: "1234567890",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 3,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 22",
    province: "Province 22",
    cityTown: "City 22",
    address: "Address 22",
    firstName: "Ava",
    middleName: "Madison",
    lastName: "Harris",
    telephone: "2345678901",
    mobileNumber: "0876543210",
    email: "ava@example.com",
    birthdate: "1993-08-12",
    placeOfBirth: "Place 22",
    sex: "Female",
    civilStatus: "Single",
    bloodType: "AB",
    religion: "Religion 22",
    nationality: "Nationality 22",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "David Harris",
    emergencyContactNumber: "2345678901",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 23",
    mainSourceofIncome: "Business",
    mainSourceofIncomeAmount: 70000,
    otherSourceofIncome: "Freelancing",
    otherSourceofIncomeAmount: 20000,
    nameofOrganization: "Org 22",
    memberSince: "2017-01-15",
    positioninOrganization: "Coordinator",
    nameofSpouse: "Spouse 22",
    numberofchildren: 0,
    spouseContactnum: "2345678901",
    numberofchildreninSchool: 0,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 1,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 23",
    province: "Province 23",
    cityTown: "City 23",
    address: "Address 23",
    firstName: "Liam",
    middleName: "Benjamin",
    lastName: "Lee",
    telephone: "3456789012",
    mobileNumber: "0765432109",
    email: "liam@example.com",
    birthdate: "1988-03-05",
    placeOfBirth: "Place 23",
    sex: "Male",
    civilStatus: "Divorced",
    bloodType: "A",
    religion: "Religion 23",
    nationality: "Nationality 23",
    highestEducationalAttainment: "PhD",
    emergencyContact: "Sarah Lee",
    emergencyContactNumber: "3456789012",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 24",
    mainSourceofIncome: "Consulting",
    mainSourceofIncomeAmount: 80000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 23",
    memberSince: "2015-03-20",
    positioninOrganization: "Manager",
    nameofSpouse: "Spouse 23",
    numberofchildren: 3,
    spouseContactnum: "3456789012",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 24",
    province: "Province 24",
    cityTown: "City 24",
    address: "Address 24",
    firstName: "Ethan",
    middleName: "Michael",
    lastName: "Thomas",
    telephone: "4567890123",
    mobileNumber: "0654321098",
    email: "ethan@example.com",
    birthdate: "1990-06-30",
    placeOfBirth: "Place 24",
    sex: "Male",
    civilStatus: "Single",
    bloodType: "O",
    religion: "Religion 24",
    nationality: "Nationality 24",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Emily Thomas",
    emergencyContactNumber: "4567890123",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 25",
    mainSourceofIncome: "Tech Startup",
    mainSourceofIncomeAmount: 120000,
    otherSourceofIncome: "Consulting",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 24",
    memberSince: "2019-05-20",
    positioninOrganization: "Consultant",
    nameofSpouse: "Spouse 24",
    numberofchildren: 1,
    spouseContactnum: "4567890123",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 25",
    province: "Province 25",
    cityTown: "City 25",
    address: "Address 25",
    firstName: "Charlotte",
    middleName: "Grace",
    lastName: "Clark",
    telephone: "5678901234",
    mobileNumber: "0543210987",
    email: "charlotte@example.com",
    birthdate: "1987-12-15",
    placeOfBirth: "Place 25",
    sex: "Female",
    civilStatus: "Married",
    bloodType: "B",
    religion: "Religion 25",
    nationality: "Nationality 25",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Mark Clark",
    emergencyContactNumber: "5678901234",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 26",
    mainSourceofIncome: "Government Job",
    mainSourceofIncomeAmount: 90000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 40000,
    nameofOrganization: "Org 25",
    memberSince: "2016-06-30",
    positioninOrganization: "CEO",
    nameofSpouse: "Spouse 25",
    numberofchildren: 2,
    spouseContactnum: "5678901234",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 4,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 26",
    province: "Province 26",
    cityTown: "City 26",
    address: "Address 26",
    firstName: "Amelia",
    middleName: "Rose",
    lastName: "Parker",
    telephone: "6789012345",
    mobileNumber: "0432109876",
    email: "amelia@example.com",
    birthdate: "1983-09-15",
    placeOfBirth: "Place 26",
    sex: "Female",
    civilStatus: "Married",
    bloodType: "A",
    religion: "Religion 26",
    nationality: "Nationality 26",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Laura Parker",
    emergencyContactNumber: "6789012345",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 27",
    mainSourceofIncome: "Engineering",
    mainSourceofIncomeAmount: 95000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 50000,
    nameofOrganization: "Org 26",
    memberSince: "2014-04-05",
    positioninOrganization: "Engineer",
    nameofSpouse: "Spouse 26",
    numberofchildren: 2,
    spouseContactnum: "6789012345",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 3,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 27",
    province: "Province 27",
    cityTown: "City 27",
    address: "Address 27",
    firstName: "Oliver",
    middleName: "Jacob",
    lastName: "Evans",
    telephone: "7890123456",
    mobileNumber: "0321098765",
    email: "oliver@example.com",
    birthdate: "1992-04-20",
    placeOfBirth: "Place 27",
    sex: "Male",
    civilStatus: "Single",
    bloodType: "AB",
    religion: "Religion 27",
    nationality: "Nationality 27",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Sophie Evans",
    emergencyContactNumber: "7890123456",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 28",
    mainSourceofIncome: "Business",
    mainSourceofIncomeAmount: 70000,
    otherSourceofIncome: "Freelancing",
    otherSourceofIncomeAmount: 20000,
    nameofOrganization: "Org 27",
    memberSince: "2017-01-15",
    positioninOrganization: "Coordinator",
    nameofSpouse: "Spouse 27",
    numberofchildren: 0,
    spouseContactnum: "7890123456",
    numberofchildreninSchool: 0,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 1,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 28",
    province: "Province 28",
    cityTown: "City 28",
    address: "Address 28",
    firstName: "Mia",
    middleName: "Elizabeth",
    lastName: "Morris",
    telephone: "8901234567",
    mobileNumber: "0210987654",
    email: "mia@example.com",
    birthdate: "1996-01-05",
    placeOfBirth: "Place 28",
    sex: "Female",
    civilStatus: "Divorced",
    bloodType: "O",
    religion: "Religion 28",
    nationality: "Nationality 28",
    highestEducationalAttainment: "PhD",
    emergencyContact: "David Morris",
    emergencyContactNumber: "8901234567",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 29",
    mainSourceofIncome: "Consulting",
    mainSourceofIncomeAmount: 80000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 28",
    memberSince: "2015-03-20",
    positioninOrganization: "Manager",
    nameofSpouse: "Spouse 28",
    numberofchildren: 3,
    spouseContactnum: "8901234567",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 29",
    province: "Province 29",
    cityTown: "City 29",
    address: "Address 29",
    firstName: "William",
    middleName: "Henry",
    lastName: "Walker",
    telephone: "9012345678",
    mobileNumber: "0109876543",
    email: "william@example.com",
    birthdate: "1998-06-15",
    placeOfBirth: "Place 29",
    sex: "Male",
    civilStatus: "Single",
    bloodType: "O",
    religion: "Religion 29",
    nationality: "Nationality 29",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Emily Walker",
    emergencyContactNumber: "9012345678",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 30",
    mainSourceofIncome: "Tech Startup",
    mainSourceofIncomeAmount: 120000,
    otherSourceofIncome: "Consulting",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 29",
    memberSince: "2019-05-20",
    positioninOrganization: "Consultant",
    nameofSpouse: "Spouse 29",
    numberofchildren: 1,
    spouseContactnum: "9012345678",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 30",
    province: "Province 30",
    cityTown: "City 30",
    address: "Address 30",
    firstName: "Sophia",
    middleName: "Emma",
    lastName: "Young",
    telephone: "0123456789",
    mobileNumber: "1098765432",
    email: "sophia@example.com",
    birthdate: "1985-11-20",
    placeOfBirth: "Place 30",
    sex: "Female",
    civilStatus: "Married",
    bloodType: "B",
    religion: "Religion 30",
    nationality: "Nationality 30",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Mark Young",
    emergencyContactNumber: "0123456789",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 31",
    mainSourceofIncome: "Government Job",
    mainSourceofIncomeAmount: 90000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 40000,
    nameofOrganization: "Org 30",
    memberSince: "2016-06-30",
    positioninOrganization: "CEO",
    nameofSpouse: "Spouse 30",
    numberofchildren: 2,
    spouseContactnum: "0123456789",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 4,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 31",
    province: "Province 31",
    cityTown: "City 31",
    address: "Address 31",
    firstName: "Jacob",
    middleName: "Logan",
    lastName: "Martinez",
    telephone: "1234567890",
    mobileNumber: "0987654321",
    email: "jacob@example.com",
    birthdate: "1993-03-25",
    placeOfBirth: "Place 31",
    sex: "Male",
    civilStatus: "Married",
    bloodType: "A",
    religion: "Religion 31",
    nationality: "Nationality 31",
    highestEducationalAttainment: "Master's Degree",
    emergencyContact: "Sophie Martinez",
    emergencyContactNumber: "1234567890",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 32",
    mainSourceofIncome: "Engineering",
    mainSourceofIncomeAmount: 95000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 50000,
    nameofOrganization: "Org 31",
    memberSince: "2014-04-05",
    positioninOrganization: "Engineer",
    nameofSpouse: "Spouse 31",
    numberofchildren: 2,
    spouseContactnum: "1234567890",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 3,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 32",
    province: "Province 32",
    cityTown: "City 32",
    address: "Address 32",
    firstName: "Emma",
    middleName: "Grace",
    lastName: "Garcia",
    telephone: "2345678901",
    mobileNumber: "0876543210",
    email: "emma@example.com",
    birthdate: "1990-10-12",
    placeOfBirth: "Place 32",
    sex: "Female",
    civilStatus: "Single",
    bloodType: "AB",
    religion: "Religion 32",
    nationality: "Nationality 32",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "David Garcia",
    emergencyContactNumber: "2345678901",
    emergrncyRelationship: "Brother",
    emergrncyAddress: "Address 33",
    mainSourceofIncome: "Business",
    mainSourceofIncomeAmount: 70000,
    otherSourceofIncome: "Freelancing",
    otherSourceofIncomeAmount: 20000,
    nameofOrganization: "Org 32",
    memberSince: "2017-01-15",
    positioninOrganization: "Coordinator",
    nameofSpouse: "Spouse 32",
    numberofchildren: 0,
    spouseContactnum: "2345678901",
    numberofchildreninSchool: 0,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 1,
    numberofUnemployedfammem: 0,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 33",
    province: "Province 33",
    cityTown: "City 33",
    address: "Address 33",
    firstName: "Aiden",
    middleName: "James",
    lastName: "Rodriguez",
    telephone: "3456789012",
    mobileNumber: "0765432109",
    email: "aiden@example.com",
    birthdate: "1988-05-05",
    placeOfBirth: "Place 33",
    sex: "Male",
    civilStatus: "Divorced",
    bloodType: "A",
    religion: "Religion 33",
    nationality: "Nationality 33",
    highestEducationalAttainment: "PhD",
    emergencyContact: "Sarah Rodriguez",
    emergencyContactNumber: "3456789012",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 34",
    mainSourceofIncome: "Consulting",
    mainSourceofIncomeAmount: 80000,
    otherSourceofIncome: "Investments",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 33",
    memberSince: "2015-03-20",
    positioninOrganization: "Manager",
    nameofSpouse: "Spouse 33",
    numberofchildren: 3,
    spouseContactnum: "3456789012",
    numberofchildreninSchool: 2,
    numberofchildrenoutSchool: 1,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },
  {
    userIdNumber: uuidv4(),
    region: "Region 34",
    province: "Province 34",
    cityTown: "City 34",
    address: "Address 34",
    firstName: "Lucas",
    middleName: "Alexander",
    lastName: "Martinez",
    telephone: "4567890123",
    mobileNumber: "0654321098",
    email: "lucas@example.com",
    birthdate: "1992-08-30",
    placeOfBirth: "Place 34",
    sex: "Male",
    civilStatus: "Single",
    bloodType: "O",
    religion: "Religion 34",
    nationality: "Nationality 34",
    highestEducationalAttainment: "Bachelor's Degree",
    emergencyContact: "Emily Martinez",
    emergencyContactNumber: "4567890123",
    emergrncyRelationship: "Sister",
    emergrncyAddress: "Address 35",
    mainSourceofIncome: "Tech Startup",
    mainSourceofIncomeAmount: 120000,
    otherSourceofIncome: "Consulting",
    otherSourceofIncomeAmount: 30000,
    nameofOrganization: "Org 34",
    memberSince: "2019-05-20",
    positioninOrganization: "Consultant",
    nameofSpouse: "Spouse 34",
    numberofchildren: 1,
    spouseContactnum: "4567890123",
    numberofchildreninSchool: 1,
    numberofchildrenoutSchool: 0,
    numberofEmployedfammem: 2,
    numberofUnemployedfammem: 1,
  },

  // Add more data as needed
];

// Function to initialize data (if needed)
export const initializeData = (data) => {
  data.forEach((item) => {
    if (!item.userIdNumber) {
      item.userIdNumber = uuidv4();
    }
  });
};
